<?php

namespace AppBundle\Repository;

/**
 * ExpertationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertationsRepository extends \Doctrine\ORM\EntityRepository
{
}
