<?php

namespace AppBundle\Repository;

/**
 * ExpertationsAdvancedLinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertationsAdvancedLinesRepository extends \Doctrine\ORM\EntityRepository
{
}
