<?php

namespace AppBundle\Repository;

/**
 * Expertation_LinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Expertation_LinesRepository extends \Doctrine\ORM\EntityRepository
{
}
