<?php

namespace AppBundle\Repository;

/**
 * ExpertationsAdvancedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertationsAdvancedRepository extends \Doctrine\ORM\EntityRepository
{
}
