<?php

namespace AppBundle\Repository;

/**
 * ExpertationsAdvancedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertationsAdvancedRepository extends \Doctrine\ORM\EntityRepository
{
    public $client;
    public $tipo;
    public $kw;
    public $piani_casa;
    public $riscaldamento;
    public $opere_murarie;
    public $trifase;
    public $sconto;
    public $level;
    public $square_meters;

    public function __construct() {
        return $this;
    }
}
