<?php

namespace AppBundle\Repository;

/**
 * HeatingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeatingsRepository extends \Doctrine\ORM\EntityRepository
{
}
