<?php

namespace AppBundle\Repository;

/**
 * OutletsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutletsRepository extends \Doctrine\ORM\EntityRepository
{
}
