<?php

namespace AppBundle\Repository;

/**
 * PricesAdvancedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricesAdvancedRepository extends \Doctrine\ORM\EntityRepository
{
    function findByCode($code) {
        $find = $this->findBy(['code' => $code]);
        return $find[0]->getPrice();
    }
}
