<?php

namespace AppBundle\Repository;

/**
 * Quadri_ElettriciRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Quadri_ElettriciRepository extends \Doctrine\ORM\EntityRepository
{
}
