<?php

namespace AppBundle\Repository;

/**
 * StatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByDate($type,$date,$order) {
        $qb = $this->createQueryBuilder("e");
        $qb->where( 'e.type', $type );
        $qb->andWhere('e.date', $date);
        $qb->orderBy("e.id", $order);

        return $qb->getQuery()->getResult();
    }

    public function returnType($type) {
        switch ($type) {
            case 1:
                return 'Preventivo Generato';
                break;
            case 2:
                return '';
                break;
        }
    }
}
