<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerExofskn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerExofskn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerExofskn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerExofskn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerExofskn\appProdProjectContainer(array(
    'container.build_hash' => 'Exofskn',
    'container.build_id' => '30ec3112',
    'container.build_time' => 1541432748,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerExofskn');
