<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLyqru1u\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLyqru1u/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLyqru1u.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLyqru1u\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLyqru1u\appProdProjectContainer(array(
    'container.build_hash' => 'Lyqru1u',
    'container.build_id' => '9def8fa0',
    'container.build_time' => 1535625886,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLyqru1u');
