<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.chartjs.transformer_char' shared service.

include_once $this->targetDirs[3].'/vendor/fados/chartjs-bundle/Model/Transformer/TransformerInterface.php';
include_once $this->targetDirs[3].'/vendor/fados/chartjs-bundle/Model/ChartDataTransformer.php';

return $this->services['app.chartjs.transformer_char'] = new \fados\ChartjsBundle\Model\ChartDataTransformer();
