<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.default_second_level_cache.logger_chain' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/Logging/CacheLogger.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/Logging/CacheLoggerChain.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/Logging/StatisticsCacheLogger.php';

$this->services['doctrine.orm.default_second_level_cache.logger_chain'] = $instance = new \Doctrine\ORM\Cache\Logging\CacheLoggerChain();

$instance->setLogger('statistics', new \Doctrine\ORM\Cache\Logging\StatisticsCacheLogger());

return $instance;
