<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator._.tenph' shared service.

return $this->services['service_locator._.tenph'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('authChecker' => function () {
    return ${($_ = isset($this->services['security.authorization_checker']) ? $this->services['security.authorization_checker'] : $this->getSecurity_AuthorizationCheckerService()) && false ?: '_'};
}, 'encoder' => function () {
    return ${($_ = isset($this->services['security.password_encoder']) ? $this->services['security.password_encoder'] : $this->load('getSecurity_PasswordEncoderService.php')) && false ?: '_'};
}, 'fileUploader' => function () {
    $f = function (\AppBundle\Service\FileUploader $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Service\FileUploader']) ? $this->services['AppBundle\Service\FileUploader'] : $this->services['AppBundle\Service\FileUploader'] = new \AppBundle\Service\FileUploader('users')) && false ?: '_'});
}));
