<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'intriro_csv.importer.default' shared service.

include_once $this->targetDirs[3].'/vendor/goodby/csv/src/Goodby/CSV/Import/Protocol/LexerInterface.php';
include_once $this->targetDirs[3].'/vendor/goodby/csv/src/Goodby/CSV/Import/Standard/Lexer.php';
include_once $this->targetDirs[3].'/vendor/goodby/csv/src/Goodby/CSV/Import/Standard/LexerConfig.php';

$a = new \Goodby\CSV\Import\Standard\LexerConfig();
$a->setDelimiter(';');
$a->setEnclosure('"');
$a->setEscape('\\');
$a->setToCharset('UTF-8');
$a->setFromCharset('SJIS-win');

return $this->services['intriro_csv.importer.default'] = new \Goodby\CSV\Import\Standard\Lexer($a);
