<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ExpertationsAdvancedType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('father', HiddenType::class)
            ->add('val1', HiddenType::class)
            ->add('val2', HiddenType::class)
            ->add('val3', HiddenType::class)
            ->add('val4', HiddenType::class)
            ->add('val5', HiddenType::class)
            ->add('val6', HiddenType::class)
            ->add('val7', HiddenType::class)
            ->add('val8', HiddenType::class)
            ->add('val9', HiddenType::class)
            ->add('val10', HiddenType::class)
            ->add('val11', HiddenType::class)
            ->add('val12', HiddenType::class)
            ->add('val13', HiddenType::class)
            ->add('val14', HiddenType::class)
            ->add('val15', HiddenType::class)
            ->add('val16', HiddenType::class)
            ->add('val17', HiddenType::class)
            ->add('val18', HiddenType::class)
            ->add('val19', HiddenType::class)
            ->add('val20', HiddenType::class)
            ->add('val21', HiddenType::class)
            ->add('val22', HiddenType::class)
            ->add('val23', HiddenType::class)
            ->add('val24', HiddenType::class)
            ->add('val25', HiddenType::class)
            ->add('val26', HiddenType::class)
            ->add('val27', HiddenType::class)
            ->add('val28', HiddenType::class)
            ->add('val29', HiddenType::class)
            ->add('val30', HiddenType::class)
            ->add('val31', HiddenType::class)
            ->add('val32', HiddenType::class)
            ->add('val33', HiddenType::class)
            ->add('val34', HiddenType::class)
            ->add('val35', HiddenType::class)
            ->add('val36', HiddenType::class)
            ->add('val37', HiddenType::class)
            ->add('val38', HiddenType::class)
            ->add('val39', HiddenType::class)
            ->add('val40', HiddenType::class)
            ->add('val41', HiddenType::class)
            ->add('val42', HiddenType::class)
            ->add('val43', HiddenType::class)
            ->add('val44', HiddenType::class)
            ->add('val45', HiddenType::class)
            ->add('val46', HiddenType::class)
            ->add('val47', HiddenType::class)
            ->add('val48', HiddenType::class)
            ->add('val49', HiddenType::class)
            ->add('val50', HiddenType::class)
            ->add('val51', HiddenType::class)
            ->add('val52', HiddenType::class)
            ->add('val53', HiddenType::class)
            ->add('val54', HiddenType::class)
            ->add('val55', HiddenType::class)
            ->add('val56', HiddenType::class)
            ->add('val57', HiddenType::class)
            ->add('val58', HiddenType::class)
            ->add('val59', HiddenType::class)
            ->add('val60', HiddenType::class)
            ->add('val61', HiddenType::class)
            ->add('val62', HiddenType::class)
            ->add('val63', HiddenType::class)
            ->add('val64', HiddenType::class)
            ->add('val65', HiddenType::class)
            ->add('fatherFloor', HiddenType::class)
            ->add('opt1Enabled', CheckBoxType::class, [ 'label' => 'PRIMA AGGIUNTA POSSIBILE: predisposizione per ingresso linee ENEL e TELECOM' , 'attr' => ['class' => 'custom-control-input', 'onclick' => 'checkedAddon(1)'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt1_1Value', IntegerType::class, [ 'label' => 'Tubazione flessibile in polietilene a doppia parete. Diametro esterno 50 mm' , 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt1_2Value', IntegerType::class, [ 'label' => 'Pozzetto in resina completo di coperchio carrabile 300 x 300 mm.' , 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt1_3Value', IntegerType::class, [ 'label' => 'Tubazione flessibile in polietilene a doppia parete. Diametro esterno 63mm', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt1_4Value', IntegerType::class, [ 'label' => 'Pozzetto in cemento completo di coperchio carrabile 300 x 300 mm.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt2Enabled', CheckBoxType::class, [ 'label' => 'SECONDA AGGIUNTA POSSIBILE: completamento predisposizione per domotica con Relè passo passo.' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt2_1Value', IntegerType::class, [ 'label' => 'Apparecchi modulari da inserire su quadro elettrico con attacco DIN, forniti e posti in opera. Sono compresi: il cablaggio, gli accessori, il montaggio, E’ compreso quanto altro occorre per dare il lavoro finito. E’ esclusa la quota di carpenteria. Relè passo-passo 1 contatto 16A', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt2_2Value', IntegerType::class, [ 'label' => 'Apparecchi modulari da inserire su quadro elettrico con attacco DIN, forniti e posti in opera. Sono compresi: il cablaggio, gli accessori, il montaggio, E’ compreso quanto altro occorre per dare il lavoro finito. E’ esclusa la quota di carpenteria. Trasformatore BTS secondario 24V 40VA', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt3Enabled', CheckBoxType::class, [ 'label' => 'TERZA AGGIUNTA POSSIBILE: impianto di antenna satellitare, completo di antenna ed accessori' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt3_1Value', IntegerType::class, [ 'label' => 'Impianto di ricezione di segnale TV satellitare costituito da antenna parabolica in alluminio, idonea alla ricezione di segnale TV satellitare, completa di palo e di sistemi di fissaggio su tetto, su parete o su copertura piana di qualsiasi natura, di cavi di collegamento fino all\'impianto di amplificazione. Il tutto posto in opera con tutto quanto occorre per dare il lavoro finito, in copertura a qualsiasi altezza, incluse le eventuali opere murarie per il fissaggio ed il ripristino di eventuali parti  di copertura interessate. Per antenna parabolica di diametro pari a 80 cm', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt3_2Value', IntegerType::class, [ 'label' => 'Sistema di decodificazione di segnale TV SAT, per impianto singolo, costituito da convertitore ad una o più uscite, da posizionare su alloggiamento predisposto, inclusi i cavi di collegamento delle colonne montanti, e degli accessori necessari per dare l\'opera finita e funzionante. Convertitore ad un’uscita', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt3_3Value', IntegerType::class, [ 'label' => 'Sistema di decodificazione di segnale TV SAT, per impianto singolo, costituito da convertitore ad una o più uscite, da posizionare su alloggiamento predisposto, inclusi i cavi di collegamento delle colonne montanti, e degli accessori necessari per dare l\'opera finita e funzionante. Convertitore a due uscite', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt3_4Value', IntegerType::class, [ 'label' => 'Sistema di decodificazione di segnale TV SAT, per impianto singolo, costituito da convertitore ad una o più uscite, da posizionare su alloggiamento predisposto, inclusi i cavi di collegamento delle colonne montanti, e degli accessori necessari per dare l\'opera finita e funzionante. Convertitore a quattro uscite', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt3_5Value', IntegerType::class, [ 'label' => 'Sistema di amplificazione ed equalizzazione multiswitch per la distribuzione del segnale TV SAT miscelato con segnale TV terrestre, fino a 30 prese, completo di convertitore, alimentatore, con ingressi derivati dall\'antenna parabolica, inclusi i cavi di collegamento delle colonne montanti e degli accessori necessari per dare l\'opera finita e funzionante. Sistema base con multiswitch radiale a 4 uscite', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt3_6Value', IntegerType::class, [ 'label' => 'Sistema di amplificazione ed equalizzazione multiswitch per la distribuzione del segnale TV SAT miscelato con segnale TV terrestre, fino a 30 prese, completo di convertitore, alimentatore, con ingressi derivati dall\'antenna parabolica, inclusi i cavi di collegamento delle colonne montanti e degli accessori necessari per dare l\'opera finita e funzionante. Centralina in cascata a 4 uscite', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt3_7Value', IntegerType::class, [ 'label' => 'Sistema di amplificazione ed equalizzazione multiswitch per la distribuzione del segnale TV SAT miscelato con segnale TV terrestre, fino a 30 prese, completo di convertitore, alimentatore, con ingressi derivati dall\'antenna parabolica, inclusi i cavi di collegamento delle colonne montanti e degli accessori necessari per dare l\'opera finita e funzionante. Amplificazione  finale per alimentazione fino a 60 prese', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt3_8Value', IntegerType::class, [ 'label' => 'Incremento al punto presa di servizio per presa di ricezione TV satellitare', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt3_9Value', IntegerType::class, [ 'label' => 'Cavo coassiale per impianti di antenna TV  al metro per linea dorsale', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt4Enabled', CheckBoxType::class, [ 'label' => 'QUARTA AGGIUNTA POSSIBILE: oneri di predisposizione per diffusione sonora per gli ambienti dell\'abitazione' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt4_1Value', IntegerType::class, [ 'label' => 'PUNTO PRESA DI SERVIZIO in  traccia sono escluse le opere murarie', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt4_2Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa di servizio per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiatura', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt4_3Value', IntegerType::class, [ 'label' => 'Maggiorazione per opere murarie su muratura in mattone pieno, calcestruzzo o pietra.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt5Enabled', CheckBoxType::class, [ 'label' => 'QUINTA AGGIUNTA POSSIBILE: oneri di predisposizione per impianto sorround soggiorno' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt5_1Value', IntegerType::class, [ 'label' => 'PUNTO PRESA DI SERVIZIO in  traccia sono escluse le opere murarie', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt5_2Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa di servizio per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiatura', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt5_3Value', IntegerType::class, [ 'label' => 'Maggiorazione per opere murarie su muratura in mattone pieno, calcestruzzo o pietra.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt6Enabled', CheckBoxType::class, [ 'label' => 'SESTA AGGIUNTA POSSIBILE: connettorizzazione dei punti di trasmissione dati predisposti e conteggiati nella proposta C. 				' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt6_1Value', IntegerType::class, [ 'label' => 'Incremento al punto presa di servizio per connettore tipo RJ45 con cavo UTP cat. 6', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt7Enabled', CheckBoxType::class, [ 'label' => 'SETTIMA AGGIUNTA POSSIBILE: oneri di predisposizione per videosorveglianza esterna' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt7_1Value', IntegerType::class, [ 'label' => 'PUNTO PRESA DI SERVIZIO in  traccia sono escluse le opere murarie', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt7_2Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa di servizio per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiatura', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt7_3Value', IntegerType::class, [ 'label' => 'Maggiorazione per opere murarie su muratura in mattone pieno, calcestruzzo o pietra.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt8Enabled', CheckBoxType::class, [ 'label' => 'OTTAVA AGGIUNTA POSSIBILE: oneri di predisposizione per sistema di rilevazione allarme' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt8_1Value', IntegerType::class, [ 'label' => 'PUNTO PRESA DI SERVIZIO in  traccia sono escluse le opere murarie', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt8_2Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa di servizio per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiaturaMaggiorazione per opere murarie su muratura in mattone pieno, calcestruzzo o pietra.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt8_3Value', IntegerType::class, [ 'label' => 'Maggiorazione per opere murarie su muratura in mattone pieno, calcestruzzo o pietra.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt9Enabled', CheckBoxType::class, [ 'label' => 'NONA AGGIUNTA POSSIBILE: oneri di predisposizione per impianto di rilevazione fumi' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt9_1Value', IntegerType::class, [ 'label' => 'PUNTO PRESA DI SERVIZIO in  traccia sono escluse le opere murarie', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt9_2Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa di servizio per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiatura', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt9_3Value', IntegerType::class, [ 'label' => 'Maggiorazione per opere murarie su muratura in mattone pieno, calcestruzzo o pietra.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt10Enabled', CheckBoxType::class, [ 'label' => 'DECIMA AGGIUNTA POSSIBILE: predisposizioni per rilevatori sonde allagamento e gas' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt10_1Value', IntegerType::class, [ 'label' => 'PUNTO PRESA DI SERVIZIO in  traccia sono escluse le opere murarie', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt10_2Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa di servizio per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiatura', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt10_3Value', IntegerType::class, [ 'label' => 'PUNTO PRESA DI SERVIZIO in  traccia sono escluse le opere murarie', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt10_4Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa di servizio per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiatura', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt10_5Value', IntegerType::class, [ 'label' => 'PUNTO PRESA DI SERVIZIO in  traccia sono escluse le opere murarie', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt10_6Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa di servizio per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiatura', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt10_7Value', IntegerType::class, [ 'label' => 'PUNTO PRESA DI SERVIZIO in  traccia sono escluse le opere murarie', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt10_8Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa di servizio per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiatura', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt10_9Value', IntegerType::class, [ 'label' => 'Maggiorazione per opere murarie su muratura in mattone pieno, calcestruzzo o pietra.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt11Enabled', CheckBoxType::class, [ 'label' => 'UNDICESIMA AGGIUNTA POSSIBILE: oneri di predisposizione per motorizzazione di tapparelle, persiane, zanzariere, tende e/o oscuranti' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt11_1Value', IntegerType::class, [ 'label' => 'PUNTO PRESA DI SERVIZIO in  traccia sono escluse le opere murarie', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt11_2Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa di servizio per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiatura', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt11_3Value', IntegerType::class, [ 'label' => 'Canalizzazione per P.to Presa in traccia per distanza non superiori a 60 mt. Sono esclusi i conduttori e le opere murarie.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt11_4Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiatura', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt11_5Value', IntegerType::class, [ 'label' => 'Maggiorazione per opere murarie su muratura in mattone pieno, calcestruzzo o pietra.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt12Enabled', CheckBoxType::class, [ 'label' => 'DODICESIMA AGGIUNTA POSSIBILE: oneri per passaggio cavi e collegamento di motorizzazioni per tapparelle, persiane, zanzariere, tende e/o oscuranti.				' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt12_1Value', IntegerType::class, [ 'label' => 'Incremento al punto presa di servizio per impianto di comando di motori monofasi o in c.c. di piccola potenza (serrande meccanizzate etc.). Con pulsante doppio senza chiave.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt12_2Value', IntegerType::class, [ 'label' => 'COMPENSO AGGIUNTIVO AL PUNTO ALLACCIO ELETTRICO PER COLLEGAMENTO AD APPARECCHIATURA DI CONTROLLO E/O COMANDO. Per collegamento motore tenda', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt12_3Value', IntegerType::class, [ 'label' => 'PUNTO ALLACCIO PER PRESA MONOFASE O TRIFASE SU CANALIZZAZIONE IN TRACCIA O SU TUBAZIONE IN VISTA CON CAVO NON PROPAGANTE L\'INCENDIO. Per allaccio monofase con carico max 16A', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt13Enabled', CheckBoxType::class, [ 'label' => 'TREDICESIMA AGGIUNTA POSSIBILE: centralino telefonico con 2 linee esterne e 8 linee interne.				' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt13_1Value', IntegerType::class, [ 'label' => 'Centralino tipo appartamento incassato a parete 24  moduli.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt13_2Value', IntegerType::class, [ 'label' => 'Centralino telefonico 2 linee esterno e 8 interni Chiamata alternata Trasferta senza consenso Trasferta Trasferimento di chiamata su linea esterna Trasferta su inclusione Devizione a tempo Trasferta automatica con consenso CLI - Identificativo chiamante.  Conferenza urbana Conferenza locale Modo programmazione giorno/notte Non disturbare Seguimi Chiamate interne generali a gruppi Rubrica Parcheggio linea esterna Risposta per assente su chiamate esterne Room monitor da linea urbana.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt13_3Value', IntegerType::class, [ 'label' => 'Linea telefonica in cavo multicoppie a 2 coppie al metro per linea dorsale', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt13_4Value', IntegerType::class, [ 'label' => 'Trasporto e imballo', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt14Enabled', CheckBoxType::class, [ 'label' => 'QUATTORDICESIMA AGGIUNTA POSSIBILE: impianto citofonico (solo audio)				' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt14_1Value', IntegerType::class, [ 'label' => 'Incremento al punto presa di servizio per impianto citofonico o videocitofonico, sistema a 2 fili. Per impianto base fino a 26 interni. ', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt14_2Value', IntegerType::class, [ 'label' => 'Incremento al punto presa di servizio per impianto citofonico  per ogni posto audio interno', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt14_3Value', IntegerType::class, [ 'label' => 'Incremento al punto presa di servizio per audio interno intercomunicante.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt14_4Value', IntegerType::class, [ 'label' => 'Incremento al punto presa di servizio per ogni posto esterno audio (PORTER) fino a 2 chiamate.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt14_5Value', IntegerType::class, [ 'label' => 'LINEA IN CAVO LONWORKS PER CONNESSIONI DI RETE TIPO AWG22.  Linea in cavo LonWorks per connessioni di rete tipo AWG22 a due conduttori (una coppia: 2x0,60mm)Twistato e non schermato, con isolamento 1 kV', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt14_6Value', IntegerType::class, [ 'label' => 'Trasporto e imballo', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt15Enabled', CheckBoxType::class, [ 'label' => 'QUINDICESIMA AGGIUNTA POSSIBILE: impianto videocitofonico a colori in esecuzione a muro				' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt15_1Value', IntegerType::class, [ 'label' => 'Incremento al punto presa di servizio per impianto citofonico o videocitofonico, sistema a 2 fili. Per impianto base fino a 26 interni. ', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt15_2Value', IntegerType::class, [ 'label' => 'Per ogni posto interno con monitor a colori.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt15_3Value', IntegerType::class, [ 'label' => 'Incremento al punto presa di servizio per audio interno intercomunicante.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt15_4Value', IntegerType::class, [ 'label' => 'Per ogni posto esterno video fino a due chiamate.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt15_5Value', IntegerType::class, [ 'label' => 'Incremento per derivatore di piano audio/video fino a 4 derivati.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt15_6Value', IntegerType::class, [ 'label' => 'LINEA IN CAVO LONWORKS PER CONNESSIONI DI RETE TIPO AWG22.  Linea in cavo LonWorks per connessioni di rete tipo AWG22 a due conduttori (una coppia: 2x0,60mm)Twistato e non schermato, con isolamento 1 kV', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt15_7Value', IntegerType::class, [ 'label' => 'Trasporto e imballo', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt16Enabled', CheckBoxType::class, [ 'label' => 'SEDICESIMA AGGIUNTA POSSIBILE: predisposizioni per rilevatori  luminosità.				' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt16_1Value', IntegerType::class, [ 'label' => 'PUNTO PRESA DI SERVIZIO in  traccia sono escluse le opere murarie', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt16_2Value', IntegerType::class, [ 'label' => 'Incremento alla canalizzazione per p.to presa di servizio per opere murarie su murature NON Intonacate. Sono esclusi: l’intonaco, la rasatura e la tinteggiatura', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt16_3Value', IntegerType::class, [ 'label' => 'Maggiorazione per opere murarie su muratura in mattone pieno, calcestruzzo o pietra.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt17Enabled', CheckBoxType::class, [ 'label' => 'DICIASSETTESIMA AGGIUNTA POSSIBILE: esempio di soluzione per la  predisposizione di  illuminazione esterna con 20 punti luce.' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt17_1Value', IntegerType::class, [ 'label' => 'Tubazione flessibile in polietilene a doppia parete. Diametro esterno 110 mm ', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt17_2Value', IntegerType::class, [ 'label' => 'Pozzetto in resina completo di coperchio carrabile 300 x 300 mm.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt17_3Value', IntegerType::class, [ 'label' => 'Canalizzazione per P.to luce in traccia per distanza non superiori a 60 mt. Sono esclusi i conduttori e le opere murarie.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt17_4Value', IntegerType::class, [ 'label' => 'Punto luce semplice con o senza conduttore di protezione posato in vista con cavo multipolare derivato da linea dorsale da canale o passerella. Per Punto luce con conduttore di protezione con cavo  idoneo alla posa per luoghi a livello di rischio basso a sigla FG16OR16.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt17_5Value', IntegerType::class, [ 'label' => 'Linea elettrica in cavo multipolare isolato. FG7OR. 3x2,5', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt17_6Value', IntegerType::class, [ 'label' => 'Giunto di derivazione realizzato con muffola in gomma in unico pezzo max 4x25 e derivato 2x1,5mmq. FG7OR', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt18Enabled', CheckBoxType::class, [ 'label' => 'DICIOTTESIMA AGGIUNTA POSSIBILE: predisposizione per impianto fotovoltaico				' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt18_1Value', IntegerType::class, [ 'label' => 'Tubazione flessibile in PVC autoestinguente serie pesante IMQ. Diametro esterno mm 32. Al metro.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt19Enabled', CheckBoxType::class, [ 'label' => 'DICIANNOVESIMA AGGIUNTA POSSIBILE: punti presa di servizio per le sonde di temperatura di ogni ambiente, tranne le due conteggiate nella proposta C.				' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt19_1Value', IntegerType::class, [ 'label' => 'Collegamento elettrico di regolazione di impianti tecnologici, eseguito sottotraccia per alimentare dal quadro elettrico di centrale o di zona una apparecchiatura di regololazione (termostato, umidostato, flussostato, sonda di temperatura, pressostato, ecc.)', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt19_2Value', IntegerType::class, [ 'label' => 'Maggiorazione per opere murarie su muratura in mattone pieno, calcestruzzo o pietra.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt20Enabled', CheckBoxType::class, [ 'label' => 'VENTESIMA AGGIUNTA POSSIBILE: cronotermostati ' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt20_1Value', IntegerType::class, [ 'label' => 'Cronotermostato Ambiente.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21Enabled', CheckBoxType::class, [ 'label' => 'VENTUNESIMA AGGIUNTA POSSIBILE: armadio rack' , 'attr' => ['class' => 'custom-control-input'] , 'label_attr' => ['class' => 'custom-control-label'], 'required' => false ])
            ->add('opt21_1Value', IntegerType::class, [ 'label' => 'Armadio rack modulare da 19” per impianti di cablaggio strutturato o consolle, realizzato in acciaio verniciato, completo di porta trasparente provvista di serratura, aperture di areazione superiori ed inferiori. Fornito e posto in opera completo di onere necessario per dare l’opera finita, ed a perfetta regola d’arte. Fino a 24 unità con profondità 600mm in esecuzione da terra completo di zoccolo.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_2Value', IntegerType::class, [ 'label' => 'Kit Ruote per armadi a pavimento. Fornito e posto in opera', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_3Value', IntegerType::class, [ 'label' => 'Pannello di alimentazione con min. 5 prese UNEL 16A+T, interruttore bipolare e spia di presenza rete.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_4Value', IntegerType::class, [ 'label' => 'PATCH PANEL PER ARMADI DI CABLAGGIO STRUTTURATO.  Patch panel per armadi di cablaggio strutturato, completo di connettori RJ45 UTP o S-FTP a 8 pin con connessione ad incisione di isolante tipo 110, su morsettiera centrale per cavo 22-26AWG, o mediante connettori singoli, completo di barra guidacavi, esclusa la quota per attestazione delle linee in ingresso ed uscita. Fornito e posto in opera a perfetta regola d’arte.  Fino a 16 porte non schermato con connettori RJ45 per cavo UTP cat. 6.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_5Value', IntegerType::class, [ 'label' => 'PATCH PANEL PER ARMADI DI CABLAGGIO STRUTTURATO.  Patch panel per armadi di cablaggio strutturato, completo di connettori RJ45 UTP o S-FTP a 8 pin con connessione ad incisione di isolante tipo 110, su morsettiera centrale per cavo 22-26AWG, o mediante connettori singoli, completo di barra guidacavi, esclusa la quota per attestazione delle linee in ingresso ed uscita. Fornito e posto in opera a perfetta regola d’arte. Fino a 24 porte non schermato con connettori RJ45 per cavo UTP cat. 6.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_6Value', IntegerType::class, [ 'label' => 'Pannello Passa Cavi. Fornito e posto in opera', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_7Value', IntegerType::class, [ 'label' => 'Patch cord tipo UTP cat. 6  fino a 1 m.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_8Value', IntegerType::class, [ 'label' => 'Patch cord tipo UTP cat. 6  fino a 3 m.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_9Value', IntegerType::class, [ 'label' => 'Incremento alla singola porta per attestazione conduttori e certificazione.', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_10Value', IntegerType::class, [ 'label' => 'Mensola di supporto portata max. 50Kg. Profondità 600 mm', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_11Value', IntegerType::class, [ 'label' => 'Mensola di supporto portata max. 15Kg. Profondità 400 mm', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_12Value', IntegerType::class, [ 'label' => 'Pannello cieco 1 unità', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_13Value', IntegerType::class, [ 'label' => 'Pannello cieco 2 unità', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
            ->add('opt21_14Value', IntegerType::class, [ 'label' => 'Gruppo di ventilazione per circolazione forzata di aria ad una ventola', 'attr' => ['class' => 'custom-form-control'] , 'data' => '0'  ])
        ;
    }/**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\ExpertationsAdvanced'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_expertationsadvanced';
    }


}
