<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\SecurityController:login' => function () {
    return ${($_ = isset($this->services['service_locator.jwewuuw']) ? $this->services['service_locator.jwewuuw'] : $this->load('getServiceLocator_JwewuuwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SettingsController:AjaxSUAAction' => function () {
    return ${($_ = isset($this->services['service_locator.hd_5bqv']) ? $this->services['service_locator.hd_5bqv'] : $this->load('getServiceLocator_Hd5bqvService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SettingsController:SettingsUserEditAction' => function () {
    return ${($_ = isset($this->services['service_locator.vuxplsm']) ? $this->services['service_locator.vuxplsm'] : $this->load('getServiceLocator_VuxplsmService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SettingsController:settingsUserPasswordResetAction' => function () {
    return ${($_ = isset($this->services['service_locator.i3nl.uy']) ? $this->services['service_locator.i3nl.uy'] : $this->load('getServiceLocator_I3nl_UyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SecurityController::login' => function () {
    return ${($_ = isset($this->services['service_locator.jwewuuw']) ? $this->services['service_locator.jwewuuw'] : $this->load('getServiceLocator_JwewuuwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SettingsController::AjaxSUAAction' => function () {
    return ${($_ = isset($this->services['service_locator.hd_5bqv']) ? $this->services['service_locator.hd_5bqv'] : $this->load('getServiceLocator_Hd5bqvService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SettingsController::SettingsUserEditAction' => function () {
    return ${($_ = isset($this->services['service_locator.vuxplsm']) ? $this->services['service_locator.vuxplsm'] : $this->load('getServiceLocator_VuxplsmService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SettingsController::settingsUserPasswordResetAction' => function () {
    return ${($_ = isset($this->services['service_locator.i3nl.uy']) ? $this->services['service_locator.i3nl.uy'] : $this->load('getServiceLocator_I3nl_UyService.php')) && false ?: '_'};
})));
