<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOzvifsh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOzvifsh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOzvifsh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOzvifsh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOzvifsh\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ozvifsh',
    'container.build_id' => 'c94efe52',
    'container.build_time' => 1544114272,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOzvifsh');
