<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxshuxd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxshuxd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVxshuxd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVxshuxd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVxshuxd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vxshuxd',
    'container.build_id' => 'be6b2294',
    'container.build_time' => 1536576136,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxshuxd');
